name: Publish

on:
  push:
    tags:
      - "v*" # Se ejecutará con cualquier tag que empiece con "v" (ej: v1.0.0, v2.1)
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Pack
        run: dotnet pack Resolute/Resolute.csproj -c Release --no-build --output ./nupkgs

      - name: Verify NuGet API Key
        shell: bash
        run: |
          if [ -z "$NUGET_API_KEY" ]; then
            echo "ERROR: NUGET_API_KEY is empty."
            exit 1
          fi

          echo "NUGET_API_KEY found."
          echo "Length: ${#NUGET_API_KEY}"

      - name: List generated packages
        run: ls -lah ./nupkgs

      - name: Push to NuGet.org
        shell: bash
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key "$NUGET_API_KEY" \
            --skip-duplicate \
            --verbosity detailed
